application_settings:
  port: 8000
database_settings:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client_settings:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "secret-token"
  timeout_milliseconds: 10000
