application_settings:
  port: 8000
  base_url: "http://127.0.0.1"
  hmac_secret: "this-is-the-hmac-secret-no-one-should-know22344"
  redis_uri: "redis://127.0.0.1:6379"
database_settings:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
email_client_settings:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "secret-token"
  timeout_milliseconds: 10000
